[package]
name = "aabb-quadtree"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

description="A quadtree that maps bounding-boxes to elements"
license="MIT/Apache-2.0"

[dependencies]
fnv = "1.*.*"
euclid= "0.16.*"
